FROM python

RUN apt-get install wget
RUN pip install pandas sqlalchemy psycopg2-binary

# INSTALL DEPENDENCIES FOR "read_parquet"
RUN pip install pyarrow
RUN pip install fastparquet


WORKDIR /app

COPY ingestion.py ingestion.py

ENTRYPOINT ["python", "ingestion.py"]